### PR TITLE
Cross-compile for SBT 1.0. Closes #10

### LINKED ISSUE #10: Cross-publish for sbt-1.0

### PR DESCRIPTION
**Pull request by chrisbenincasa**
Implements cross-compilation for SBT 1.x line while still supporting the 0.13.x line. Closes #10 

A few notes on the chosen path here:
* In order to attempt to reduce the amount of changes here, I opted to copy `plugin.scala` and `blockade.scala` to a separate `scala-2.12` folder. The reason for this is because of SBT's modularization - for most classes, we're still able to reference via `sbt.{XYZ}`, there are however a few exceptions:
  * `ModuleFilter` is not exposed in this manner in SBT 1.x and thus we have to include `sbt.librarymanagement`. `ModuleFilter` is a large part of `blockade.scala`, so I opted to just copy the file for both `scala-2.10` and `scala-2.12` with only the namespace changed. Of course, this kind of stinks, since the implementation is now split, but it saves the initial headache of ripping up this huge file to extract commonalities 
  * For SBT 1.x, some minor changes had to be made to `plugin.scala` to implement the `blockade` task. Specifically, running `moduleGraphSbtTask.value` inside of a task now throws an error due to macro changes in the SBT 1.x line. The `blockade` task needs to be redefined as a `taskDyn`. **This might be an OK change to backport to the 0.13.x line implementation**
* I had to disable `fork := true` due to a serialization backwards incompatibility in the `ForkConfiguration` class from SBT. When `fork := true` is set, running scalatest with SBT 1.0 fails with this error: 
```
[error] Uncaught exception when running tests: java.io.InvalidClassException: sbt.ForkConfiguration; local class incompatible: 
stream classdesc serialVersionUID = -4842665101791919492, local class serialVersionUID = 7284856321565673083
```
* `scripted` tests now run `clean` before each script in order to ensure that `^scripted` (cross plugin compilation) works.

I would love some feedback/suggestions here on anyway to improve this implementation. Our company uses Blockade (and we love it!) and it's the last plugin we need compiled for SBT 1.x before we can make the company-wide switch!

### CODE REVIEW

**Comment by rossabaker** [comment]
Thanks for this!

Is it worth considering dropping support for 0.13, given that the feature set is barely changing and that most of the world has moved on to sbt-1.0?  The hard work is done, and maybe we can simplify it.

I'm rerunning the build on 29a932a.  It was a hang.  Want to see if it was transient or an actual problem.

**Comment by chrisbenincasa** [comment]
@rossabaker Totally! Dropping support for 0.13 would certainly simplify this.

**Comment by chrisbenincasa** [comment]
@rossabaker new commit drops support for SBT 0.13 (and bumps the project itself to use SBT 1.1.6). Lemme know what you think! If all is well I'll squash this commits up.

**Review by rossabaker — APPROVED** [review]
I'm not an expert on the sbt internals, but the approach looks sound and well tested.

**Comment by chrisbenincasa** [comment]
Awesome. @rossabaker I squashed the commits into one. Should be good to go now!

**Comment by chrisbenincasa** [comment]
Actually @rossabaker before this is merged, it might be useful to have cross compilation for SBT 1.0 and 1.1. There are lots of plugins that are not yet released for SBT 1.1, so having 1.0 in there might be a good idea. However, one issue is that the release process defined in sbt-rig might need to be amended to allow for cross publishing. 

Alternatively, we could hold off on 1.1.x until sbt-rig is setup to handle cross plugin compilation and just use sbtVersion = 1.0.4 here.

**Comment by chrisbenincasa** [comment]
I've changed the global sbtVersion for the plugin to 1.0.4 so that most dependent projects will be compatible (since many other plugins don't support 1.1 just yet, from what it seems). This can be updated to cross compile for `1.{0,1}` once/if sbt-rig is appropriately updated

**Comment by rossabaker** [comment]
1.0 and 1.1 are fully compatible, no?  I upgraded from 1.0 to 1.1 and never had any problems.  I don't think this needs to be cross compiled at all?

**Comment by chrisbenincasa** [comment]
@rossabaker That's what I thought too - I was unsure that if you had a project that was SBT 1.1 and attempted to use plugins that were only compiled for 1.0 (e.g. an Ivy path like `com.eed3si9n/sbt-assembly/scala_2.12/sbt_1.0/0.14.6/`) if that would cause a dependency resolution issue. Though, I just did a quick test and that doesn't seem to be the case

**EDIT**: reverted the SBT version back to 1.1.6 in the build here.

**Comment by chrisbenincasa** [comment]
@rossabaker think this is good to go if you feel comfortable with it!

**Comment by rossabaker** [comment]
Thanks!  I just released this as 1.0.0.

**Comment by chrisbenincasa** [comment]
Awesome! Thank you!

**Pull request merged**
