### PR TITLE
Adding URI resolver to allow for custom resolution

### PR DESCRIPTION
**Pull request by devshorts**
Adding a way to hook into URI resolution. The use case here is if you want to load the contents of a URI from a private source (like a non-public S3 bucket) you can bypass the default URI resolution and provide your own.  This can be useful for internal companies who want to leverage blockade

### CODE REVIEW

**Review by rossabaker — COMMENTED** [review]
Thanks!  I like this if Travis likes it.

Would you mind bumping version.sbt to 0.3.0-SNAPSHOT since this adds a key?  We have an automated release process, and that will preserve semver since we added functionality.

**Comment by devshorts** [comment]
@rossabaker thanks for the review! SemVer bumped ✔️

**Comment by devshorts** [comment]
@rossabaker thanks for merging.  Is there an ETA on when this build will be released?

**Comment by rossabaker** [comment]
It's automated and it's done.  Version 0.3.39.  Thanks for the enhancement!

**Comment by devshorts** [comment]
@rossabaker thanks so much!

**Pull request merged**
