### PR TITLE
Add blockadeFailTransitive which gives ability to cause errors on tra…

### PR DESCRIPTION
**Pull request by adelbertc**
…nsitive dependency violations

### CODE REVIEW

**Comment by timperrett** [comment]
@adelbertc interesting addition. What's the use case for this? We had previously made the choice to only make transitive problems a warning, because historically people have been unable to fix their upstream dependencies themselves (i.e. they just consume a library, not author it)

**Comment by adelbertc** [comment]
@timperrett Our use case is that we have identified dependencies with vulnerabilities that we use and want to make sure people move off of them soon, even if they are transitive.

I agree transitive dependencies are hard to fix, much more so than direct dependencies, which is why I made it be `false` by default :-)

**Comment by timperrett** [comment]
@adelbertc thats a fair use case - its certainly a heavy hammer, and just organizationally i would encourage that its seldom used and that sufficient migration time is given, otherwise people get jaded pretty fast and its all uphill from there :-D

**Comment by adelbertc** [comment]
@timperrett Welp I think there is a bug in the code, it seems like it will fail even if `blockadeFailTransitive := true` but the expiration date is not passed yet, investigating..

**Comment by timperrett** [comment]
@adelbertc whatever happened with this? I reverted this in #5

**Comment by adelbertc** [comment]
@timperrett I am *this* close to finishing a fixed PR! Was working on this today, hopefully PR tomorrow!

**Pull request merged**
